### ISSUE TITLE
Issue with pickled custom_colormaps

### ISSUE THREAD

**Issue by watkinrt** [breedlun/clearplot#1]
I get the following error from params.py when I try to import clearplot:

```
import clearplot
Traceback (most recent call last):

  File "<ipython-input-1-eababf22c3b1>", line 1, in <module>
    import clearplot

  File "C:\Users\rtwatkin\Documents\Code\clearplot\clearplot\__init__.py", line 45, in <module>
    import params

  File "C:\Users\rtwatkin\Documents\Code\clearplot\clearplot\params.py", line 146, in <module>
    c_maps = _pickle.load(_c_maps_file)

ImportError: No module named copy_reg
```

I'm pretty sure this is due to either cross-platform issues (I'm trying to load it on Windows and I imagine it was created on OS X) or different python versions. When you created custom_colormaps.pkl, did you write it in binary mode ('wb')? It looks like you did as you try to open it in binary mode ('rb'). If that is the case, than we are probably running into issues due to conflicting python versions (I'm running Python 2.7.9 from Anaconda's 2.2.0).

**Comment by breedlun** [comment]
Huh.  I have not had any trouble with pickled files and I often switch between OS X and Red Hat Linux.  Windows is another beast, though.

In case custom_colormaps.pkl was written without binary mode, I went ahead and re-pickled it, making sure to use 'wb' when I opened the file.  I just pushed the changes.  Can you give it another try?

In case it matters, I am on Python 2.7.6 from Enthought Canopy.

**Comment by watkinrt** [comment]
Hmmm, that didn’t seem to work. From looking around at forums, it seems to be a conflicting Python version issue (which is lame in my mind as pickled files should work across the board). I’m currently working on a “Colors” class which I used to use which allows you to use English names to access commonly used colors and colormaps. For example: commands like Colors.Blue or Colors.RainbowMap would return the respective color or colormap. This abstraction makes changing a color scheme very easy. This should also allow us to move from using a pickled version of your colormaps as I can just hardcode them into the class. Hopefully I send a push request by the end of tomorrow.

**Comment by breedlun** [comment]
It sounds like your colormap class is just like my c_maps dictionary.  You access each specific colormap by supplying the dictionary key, which is a string.  If so, we might as well just stick with the simpler dictionary.  We could certainly hard code the dictionary, instead of bothering with pickle, since it seems to be finicky.  

Perhaps you had something else in mind with your colormap class, though.  Do you want to something like add methods to the colormap class?

**Comment by breedlun** [comment]
Can you try one more time with loading custom_colormaps.pkl?  I just refreshed it again on github.

**Comment by watkinrt** [comment]
I figured out the problem (although I’m not currently sure of a solution yet). It appears that GitHub automatically changes the end-of-line character (EOL) depending on your OS. This is find for the .py files, but it messes up the pickled files. If I take the custom_colormaps.pkl file and revert the EOL character to Unix, everything works fine (which explains why the file you emailed me worked because it retained the Unix EOL character). If I then switch it back to the EOL character for Windows, it stops working again. 

 

Not sure how to fix this as of now.

**Comment by watkinrt** [comment]
It is similar to your c_maps dictionary. I created the class in Matlab because it only had limited color manipulation tools. So I added methods to the class to convert between rbg, hsv and hsl, along with darking and lightening colors. In the context of Python, I think this translates into having a dictionary file and some utility functions. So, what you have should be fine.

**Comment by breedlun** [comment]
Wow.  Github changing the EOL characters is downright evil.  Why does it do that?  Well, the simple solution is to hard code the colormaps, like you were planning on.

As for the colormap class vs. colormap dictionary question, I now understand your thinking.  A base class with the methods to convert between rgb, hsv, and hsl, as well as darkening and lighting colors sounds good to me.  Yes, those could be separate utility functions, but then the user would have to know where to find those utility functions.  It seems better to just have them on the base class, since they are generally applicable to all colormaps.

**Comment by breedlun** [comment]
Here is another reason to ditch the pickled custom_colormaps.  I just registered clearplot on PyPI, so anyone can easily install it with pip or easy_install.  However, when I tested it, I got the following error upon importing clearplot,

    _c_maps_file = open(_os.path.join(_os.path.dirname(__file__),'custom_colormaps.pkl'), 'rb')
    IOError: [Errno 2] No such file or directory: '/Users/Ben/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/clearplot/custom_colormaps.pkl'

Apparently, PyPI is not set up to distribute pickled files.

**Comment by watkinrt** [comment]
Interesting. I’ll try to push my color class to GitHub this weekend if I get a chance.

**Comment by breedlun** [comment]
@watkinrt , I went ahead and hardcoded the color maps into a new module called `colors`.  I checked and this resolved the issue with PyPI.  When you have a free moment, can you verify that it resolves the github EOL character issue you found?

BTW, I left the color maps as dictionary entries.  You can make the color maps instances of your color map class whenever you get around to it.  

Also, to finish setting things up on PyPI, we need to make it so that pip will automatically install the custom fonts upon installation.  I think this requires messing with the setup.py file.

**Comment by watkinrt** [comment]
I went ahead and hardcoded the color maps into a new module called colors. I checked and this resolved the issue with PyPI. When you have a free moment, can you verify that it resolves the github EOL character issue you found?

Okay sounds good. This appeared to fix the issue I was having with github. 

 

I’ve been toying around with the best way to implement the color module. I’ll let you know when I finish up.

 

I tried to run the clearplot_tests script today and ran into issues with the pickled “violin_plot_data.pkl” file. I’m pretty sure this is another EOL problem (can you email me the original so that I can double check?).

 

Also, to finish setting things up on PyPI, we need to make it so that pip will automatically install the custom fonts upon installation. I think this requires messing with the setup.py file.

I can take a look at this if you want.

**Comment by breedlun** [comment]
Shoot!  I forgot about those `*.pkl` files.  I will hard code those too, or maybe turn them into `*.csv` files.

I think I have the PyPI custom fonts thing worked out.  It was good for me to take the time to understand `distutils.core.setup` a bit.

**Comment by breedlun** [comment]
Ok.  I converted the `*.pkl` files to `*.csv` files.  Can you run the tests and examples again to verify that I have fixed the problem on windows?

**Comment by breedlun** [comment]
@watkinrt confirmed over email that the `*.csv` files loaded properly on his windows machine.  All `*.pkl` files should be now removed from clearplot.
